<?php

use Laravel\Sanctum\Sanctum;

return [

    /*
    |--------------------------------------------------------------------------
    | Stateful Domains
    |--------------------------------------------------------------------------
    |
    | Requests from the following domains / hosts will receive stateful API
    | authentication cookies. Typically, these should include your local
    | and production domains so that requests from the browser work.
    |
    */

    'stateful' => explode(',', env('SANCTUM_STATEFUL_DOMAINS', sprintf(
        '%s%s',
        'localhost,localhost:3000,localhost:4200,localhost:8000,localhost:5173',
        Sanctum::currentApplicationUrlWithPort()
            ? ',' . parse_url(Sanctum::currentApplicationUrlWithPort(), PHP_URL_HOST)
            : ''
    ))),

    /*
    |--------------------------------------------------------------------------
    | Expiration Minutes
    |--------------------------------------------------------------------------
    |
    | This value controls the number of minutes until an issued token will be
    | considered expired. This will override any values set in the token's
    | "expires_at" attribute, but first-party sessions are not affected.
    |
    */

    'expiration' => env('SANCTUM_EXPIRATION', 120),

    /*
    |--------------------------------------------------------------------------
    | Token Prefix
    |--------------------------------------------------------------------------
    |
    | Sanctum can prefix new tokens in order to take advantage of numerous
    | security scanning initiatives maintained by open source platforms
    | that notify developers if they commit tokens into repositories.
    |
    | See: https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning
    |
    */

    'token_prefix' => env('SANCTUM_TOKEN_PREFIX', 'salon_'),

    /*
    |--------------------------------------------------------------------------
    | Sanctum Guards
    |--------------------------------------------------------------------------
    |
    | You may specify which guards Sanctum will authenticate while using the
    | "guard" middleware. If your application needs to authenticate guards
    | other than the default "web" guard, you may specify them here.
    |
    */

    'guard' => ['web'],

    /*
    |--------------------------------------------------------------------------
    | Personal Access Token Model
    |--------------------------------------------------------------------------
    |
    | This value defines the model that should be used to store issued tokens
    | generated by Sanctum. You are free to provide your own model that
    | extends the Sanctum personal access token model used by the app.
    |
    */

    'personal_access_token' => env('SANCTUM_PERSONAL_ACCESS_TOKEN_MODEL'),

];

